name: EP-contacts
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip=22.2.2
  - numpy=1.21.5
  - pandas=1.4.4
  - fast-histogram
  - matplotlib=3.5.2
  - statsmodels=0.13.2
  - seaborn=0.11.2
  - scipy=1.9.1
  - rpy2=3.5.10
  - r-base>=4.1
